services:
  desktop:
    build:
      dockerfile: ./Dockerfile-novnc
      args:
        USER_NAME: ${USER_NAME}
        USER_PASSWORD: ${USER_PASSWORD}
    container_name: novnc-desktop
    ports:
      - "${NOVNC_PORT}:6080"
      - "${VNC_PORT}:5901"
    shm_size: "1gb"
    environment:
      - VNC_PASSWORD=${VNC_PASSWORD}
      - VNC_RESOLUTION=${VNC_RESOLUTION}
      - VNC_DEPTH=${VNC_DEPTH}
      - VNC_PORT=${VNC_PORT}
      - NOVNC_PORT=${NOVNC_PORT}
      - LANG=${LANG}
      - TZ=${TZ}
    restart: unless-stopped