services:
  novnc-cursor:
    container_name: novnc-cursor
    build:
      dockerfile: Dockerfile-novnc-cursor
      args:
        DESKTOP_USER: ${DESKTOP_USER}
        DESKTOP_PASSWORD: ${DESKTOP_PASSWORD}
    ports:
      - "${NOVNC_PORT}:6080"
      - "${VNC_PORT}:5901"
    shm_size: "8gb"
    environment:
      - DESKTOP_USER=${DESKTOP_USER}
      - DESKTOP_PASSWORD=${DESKTOP_PASSWORD}
      - VNC_PASSWORD=${VNC_PASSWORD}
      - VNC_RESOLUTION=${VNC_RESOLUTION}
      - VNC_DEPTH=${VNC_DEPTH}
      - VNC_PORT=${VNC_PORT}
      - NOVNC_PORT=${NOVNC_PORT}
      - LANG=${LANG}
      - TZ=${TZ}
    restart: no
    volumes:
      - "${HOST_PROJECTS_DIR}:${CONTAINER_PROJECTS_DIR}"