version: "3.9"

services:
  debian-xfce-cursor:
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile-rdp-cursor
      args:
        RDP_USER: ${RDP_USER}
        RDP_PASS: ${RDP_PASS}
    ports:
      - "${RDP_PORT}:3389"
    shm_size: ${SHM_SIZE}
    restart: no
    environment:
      TZ: ${TZ}
    volumes:
      - ${HOST_PROJECTS_DIR}:${CONTAINER_PROJECTS_DIR}

  php-launchpad:
    image: php-launchpad
    build:
      context: .
      dockerfile: Dockerfile-php-launchpad
    working_dir: /app
    volumes:
      - ${HOST_PROJECTS_DIR}:/app
    environment:
      TZ: ${TZ}
    stdin_open: true
    tty: true
    profiles:
      - php